export const flavors = [
 {id:'tropical',short:'Tropical',name:'Tigrinho Tropical',lines:'TIGRINHO<br>TROPICAL',type:'Gin',accent:'#e8e95a',glow:'#a59413',bg:'#242005',bottle:'#c8a622',cap:'#e3c219',fruit:'citrus',description:'Gin e frutas tropicais em uma combinação pronta para beber. Só falta o gelo.',slug:'gin-combo-tigrinho-tropical-1l-6-unidades'},
 {id:'clt',short:'CLT',name:'CLT',lines:'COMBO<br>CLT',type:'Whisky',accent:'#8496ff',glow:'#4055cb',bg:'#111735',bottle:'#201baf',cap:'#efefe8',fruit:'ice',description:'O Combo de Litro do Trabalhador. Whisky e sabor de energético em uma garrafa de personalidade.',slug:'whisky-combo-clt-1l-6-unidades-1cwmr'},
 {id:'banana',short:'Banana',name:'Banana',lines:'COMBO<br>BANANA',type:'Whisky',accent:'#f0d559',glow:'#b39016',bg:'#292105',bottle:'#e7bd19',cap:'#101110',fruit:'banana',description:'Whisky com o toque marcante da banana. Uma combinação pronta para quem gosta de um sabor diferente.',slug:'whisky-combo-banana-1l-6-unidades-3tzbc'},
 {id:'apple',short:'Maçã verde',name:'Maçã Verde',lines:'MAÇÃ<br>VERDE',type:'Whisky',accent:'#bcdf59',glow:'#5c9c2b',bg:'#0b2917',bottle:'#92bd22',cap:'#161815',fruit:'apple',description:'O encontro do whisky com a maçã verde. Frescor e personalidade no mesmo combo.',slug:'whisky-combo-maca-verde-1l-6-unidades'},
 {id:'classic',short:'Original',name:'Original',lines:'COMBO<br>ORIGINAL',type:'Whisky',accent:'#ef78bc',glow:'#a63573',bg:'#30101f',bottle:'#131214',cap:'#121214',fruit:'ice',description:'O clássico da Mansão. Whisky e sabor de energético em uma combinação pronta para beber.',slug:'whisky-combo-1l-6-unidades'},
 {id:'dark',short:'Double Dark',name:'Double Darkness',lines:'DOUBLE<br>DARKNESS',type:'Whisky',accent:'#cacbd4',glow:'#514c75',bg:'#151423',bottle:'#222225',cap:'#101013',fruit:'dark',description:'Uma identidade escura e marcante. Conheça o Whisky Combo Double Darkness da Mansão.',slug:'whisky-combo-double-darkness-1l-6-unidades'},
 {id:'vodka',short:'Vodka',name:'Vodka',lines:'VODKA<br>COMBO',type:'Vodka',accent:'#8bddf1',glow:'#187d97',bg:'#072c32',bottle:'#52aad4',cap:'#161819',fruit:'ice',description:'Vodka e sabor de energético. O combo azul da Mansão, pronto para beber com gelo.',slug:'vodka-combo-1l-6-unidades'},
 {id:'watermelon',short:'Melancia',name:'Melancia',lines:'GIN<br>MELANCIA',type:'Gin',accent:'#ef9fc5',glow:'#a83570',bg:'#301326',bottle:'#d899ca',cap:'#121513',fruit:'melon',description:'Gin com o sabor refrescante da melancia. A combinação rosa do universo Mansão.',slug:'gin-combo-melancia-1l-6-unidades'},
 {id:'mango',short:'Manga + maracujá',name:'Manga + Maracujá',lines:'MANGA +<br>MARACUJÁ',type:'Whisky',accent:'#ff9b4e',glow:'#ca4915',bg:'#391809',bottle:'#d93310',cap:'#e82024',fruit:'mango',description:'Tigrinho Manga + Maracujá. Whisky Combo de 1 litro.',slug:'whisky-combo-tigrinho-1l-6-unidades'},
 {id:'kut',short:'Gin Kut',name:'Gin Kut Original',lines:'GIN KUT<br>ORIGINAL',type:'Gin',category:'GIN KUT',accent:'#f1e8d6',glow:'#855438',bg:'#2c221b',bottle:'#e8e2d6',cap:'#101111',fruit:'lychee',description:'Gin Kut Original de 1 litro.',slug:null}
];
export const productUrl = f => f.slug?'https://gorodamansao.com/produtos/'+f.slug+'/':'https://gorodamansao.com/';
