import * as THREE from './assets/three.module.js';
import {GLTFLoader} from './assets/GLTFLoader.js';
import {HDRLoader} from './assets/HDRLoader.js';
import {DecalGeometry} from './assets/DecalGeometry.js';

export async function createLogisticsScene(host){
 const renderer=new THREE.WebGLRenderer({canvas:host.querySelector('canvas'),alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(37,1,.1,100);camera.position.set(7,5.2,8);camera.lookAt(0,.7,0);
 scene.add(new THREE.HemisphereLight(0xfaf9df,0x284031,2.2));const light=new THREE.DirectionalLight(0xfff4ce,3.2);light.position.set(-3,8,6);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-5,right:5,top:5,bottom:-5,near:.1,far:25});light.shadow.normalBias=.035;light.shadow.bias=-.0003;light.shadow.radius=4;scene.add(light);const rim=new THREE.DirectionalLight(0xcfe9a3,2.2);rim.position.set(4,3,-3);scene.add(rim);
 const world=new THREE.Group();scene.add(world);const gltf=new GLTFLoader(),textures=new THREE.TextureLoader();
 const [warehouseAsset,vanAsset,boxAsset,workerAsset,logo]=await Promise.all(['depot','van-premium','box','worker'].map(name=>gltf.loadAsync('assets/models/logistics/'+name+'.glb')).concat(textures.loadAsync('assets/logo.webp')));
 logo.colorSpace=THREE.SRGBColorSpace;logo.anisotropy=4;
 function fit(source,maxSize){source.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(source),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),s=maxSize/Math.max(size.x,size.y,size.z),group=new THREE.Group();source.position.x-=center.x;source.position.y-=box.min.y;source.position.z-=center.z;group.add(source);group.scale.setScalar(s);source.traverse(mesh=>{if(!mesh.isMesh)return;mesh.castShadow=true;mesh.receiveShadow=true;const array=Array.isArray(mesh.material)?mesh.material:[mesh.material];const next=array.map(old=>{const material=old.clone();material.roughness=Math.max(.35,material.roughness);material.metalness=Math.min(.22,material.metalness);return material;});mesh.material=Array.isArray(mesh.material)?next:next[0];});return group;}
 const warehouse=fit(warehouseAsset.scene,4.55);warehouse.position.set(.3,.025,-1.15);world.add(warehouse);
 const van=fit(vanAsset.scene,3.45);van.position.set(-.72,.025,1.05);van.rotation.y=-Math.PI/2;van.traverse(mesh=>{if(!mesh.isMesh)return;const mats=Array.isArray(mesh.material)?mesh.material:[mesh.material];mesh.material=mats.map(mat=>{if(mat.name==='paintD'){const paint=new THREE.MeshPhysicalMaterial({color:'#315b3f',roughness:.27,metalness:.3,clearcoat:1,clearcoatRoughness:.18});paint.name='paintD';return paint;}if(mat.name==='glass'){mat.color.set('#405d58');mat.roughness=.09;mat.metalness=.12;}return mat});if(mesh.material.length===1)mesh.material=mesh.material[0];});world.add(van);
 const worker=fit(workerAsset.scene,1.28);worker.position.set(1.42,.025,1.82);worker.rotation.y=-.5;world.add(worker);
 const mixer=new THREE.AnimationMixer(workerAsset.scene),idle=workerAsset.animations.find(a=>/idle/i.test(a.name))||workerAsset.animations[0];if(idle){mixer.clipAction(idle).play();mixer.update(.1);}
 const box=fit(boxAsset.scene,.48);box.updateMatrixWorld(true);const cartonBounds=new THREE.Box3().setFromObject(box),cartonSize=cartonBounds.getSize(new THREE.Vector3()),cartonCenter=cartonBounds.getCenter(new THREE.Vector3());
 // The imported carton keeps its original geometry; the logo is printed on its front face.
 const cartonLogo=new THREE.Mesh(new THREE.PlaneGeometry(cartonSize.x*.78,cartonSize.x*.78*56/215),new THREE.MeshStandardMaterial({map:logo,color:'#163825',transparent:true,roughness:.8,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2}));cartonLogo.position.set(cartonCenter.x,cartonCenter.y,cartonBounds.max.z+.001);const brandedCarton=new THREE.Group();brandedCarton.add(box,cartonLogo);
 for(const [x,z,level,turn] of [[2,.85,0,.05],[2,.85,1,.05],[2,.85,2,.05],[2.5,.8,0,-.1],[2.5,.8,1,-.1],[2.1,1.5,0,.2],[1.1,-.15,0,0],[1.1,-.15,1,0]]){const clone=brandedCarton.clone(true);clone.position.set(x,.025+level*cartonSize.y,z);clone.rotation.y=turn;world.add(clone);}
 // Actual brand artwork is attached to the imported vehicle and warehouse.
 function sign(width,x,y,z,rotation=0){const group=new THREE.Group();const panel=new THREE.Mesh(new THREE.PlaneGeometry(width,width*.30),new THREE.MeshStandardMaterial({color:'#17382a',roughness:.65,metalness:.08,side:THREE.DoubleSide}));group.add(panel);const decal=new THREE.Mesh(new THREE.PlaneGeometry(width*.84,width*.84*56/215),new THREE.MeshBasicMaterial({map:logo,transparent:true,depthWrite:false,side:THREE.DoubleSide}));decal.position.z=.004;group.add(decal);group.position.set(x,y,z);group.rotation.y=rotation;world.add(group);return group;}
 world.updateMatrixWorld(true);const depotBox=new THREE.Box3().setFromObject(warehouse);
 sign(1.65,.35,depotBox.max.y*.58,depotBox.max.z+.025);
 // Project the actual brand artwork onto both curved side panels, rather than hanging a board in front of the van.
 const decalMaterial=new THREE.MeshStandardMaterial({map:logo,transparent:true,roughness:.42,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-4});
 for(const side of [-1,1]){const point=vanAsset.scene.localToWorld(new THREE.Vector3(side*1.015,1.5,-.93)),rotation=new THREE.Euler(0,van.rotation.y+side*Math.PI/2,0),size=new THREE.Vector3(1.9,1.9*56/215,.4).multiplyScalar(van.scale.x);van.traverse(mesh=>{if(!mesh.isMesh||mesh.material.name!=='paintD')return;const geometry=new DecalGeometry(mesh,point,rotation,size);if(geometry.attributes.position.count){const decal=new THREE.Mesh(geometry,decalMaterial);world.add(decal);}else geometry.dispose();});}
 const floor=new THREE.Mesh(new THREE.CircleGeometry(4.2,96),new THREE.MeshStandardMaterial({color:'#2b4530',roughness:.9,metalness:.04}));floor.rotation.x=-Math.PI/2;floor.position.y=.005;floor.receiveShadow=true;world.add(floor);
 const ring=new THREE.Mesh(new THREE.RingGeometry(4.16,4.19,96),new THREE.MeshBasicMaterial({color:'#9ab36b',transparent:true,opacity:.25,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.009;world.add(ring);
 let bounds,visible=true,raf=0,last=0,dragging=false,lastX=0,targetYaw=-.12,pointer=0;const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
 function render(){renderer.render(scene,camera);}
 function layout(){bounds=host.getBoundingClientRect();if(!bounds.width||!bounds.height)return;camera.aspect=bounds.width/bounds.height;const mobile=bounds.width<480;camera.position.set(mobile?9.2:7,mobile?6.3:5.2,mobile?10.5:8);camera.lookAt(0,.7,0);camera.updateProjectionMatrix();renderer.setSize(bounds.width,bounds.height,false);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.5:1.8));render();}
 new ResizeObserver(layout).observe(host);layout();await renderer.compileAsync(scene,camera);render();host.classList.add('ready');host.dataset.renderer='three';host.dataset.models='warehouse,van,worker,box';
 function schedule(){if(!raf&&visible&&!document.hidden)raf=requestAnimationFrame(loop);}
 function loop(now){raf=0;if(!visible||document.hidden)return;const dt=Math.min((now-last)/1000,.04);last=now;world.rotation.y=THREE.MathUtils.damp(world.rotation.y,targetYaw+pointer*.06,5,dt);if(!reduced)mixer.update(dt);render();if(!reduced||dragging||Math.abs(world.rotation.y-targetYaw-pointer*.06)>.001)schedule();}
 host.addEventListener('pointerdown',event=>{if(event.button!==0)return;dragging=true;lastX=event.clientX;host.setPointerCapture(event.pointerId);});host.addEventListener('pointermove',event=>{if(dragging){targetYaw=THREE.MathUtils.clamp(targetYaw+(event.clientX-lastX)*.004,-.6,.6);lastX=event.clientX;}else if(event.pointerType!=='touch'){const rect=host.getBoundingClientRect();pointer=(event.clientX-rect.left)/rect.width-.5;}schedule();});host.addEventListener('pointerup',()=>dragging=false);host.addEventListener('pointercancel',()=>dragging=false);host.addEventListener('lostpointercapture',()=>dragging=false);host.addEventListener('pointerleave',()=>{pointer=0;schedule();});host.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','Home'].includes(event.key)){event.preventDefault();targetYaw=event.key==='Home'?-.12:THREE.MathUtils.clamp(targetYaw+(event.key==='ArrowLeft'?-.12:.12),-.6,.6);schedule();}});
 new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible){last=performance.now();schedule();}else{cancelAnimationFrame(raf);raf=0;}},{threshold:.01}).observe(host);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;}else{last=performance.now();schedule();}});
 new HDRLoader().loadAsync('assets/studio.hdr').then(async hdr=>{const pmrem=new THREE.PMREMGenerator(renderer),env=pmrem.fromEquirectangular(hdr);scene.environment=env.texture;scene.environmentIntensity=.45;hdr.dispose();pmrem.dispose();await renderer.compileAsync(scene,camera);render();}).catch(()=>{});schedule();
}
